# Site settings
title: SOCO INDUSTRIAL
email: admin@socoindustrial.com
url: https://www.socoindustrial.com
description: "24/7 mobile equipment service & repair. Serving Southern Colorado - Canon City, Colorado Springs, Pueblo, Westcliffe, Cripple Creek, Hartsel, Salida. Oil changes for passenger vehicles and heavy equipment. Hoses crimped on-site. Mechanical and fabrication services. Call or text (719) 877-5139"
keywords: "oil change, hydraulic, repair, service, hose, crimp, mobile, eqipment, lube, fabrication, mechanic, Canon City, Florence, Penrose, Westcliffe, Cripple Creek, Hartsel, Salida, Buena Vista, Gunnison, Crested Butte"
skills: "<p>24/7 Mobile Equipment Service & Repair</p> <p><i>Keep Colorado Moving</i></p> <p>Call or Text: (719) 877-5139 • Email: admin@socoindustrial.com • Serving Southern Colorado</p> <p><u>HOURS</u></p><p>Monday 12:00 am - 11:59 pm</p><p>Tuesday 12:00 am - 11:59 pm</p><p>Wednesday 12:00 am - 11:59 pm</p><p>Thursday 12:00 am - 11:59 pm</p><p>Friday 12:00 am - 11:59 pm</p><p>Saturday 12:00 am - 11:59 pm</p><p>Sunday 12:00 am - 11:59 pm</p>"
meta_author: SOCO INDUSTRIAL

# Google webmaster tools
google_verify: google3b25c34b4d0757e5.html

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff9900 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: SOCO INDUSTRIAL CORPORATION
  location: Location
  social: Social Media Links
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SOCOindustrial
  - title: facebook
    url: https://www.facebook.com/socoindustrial
  - title: github
    url: https://github.com/SOCOindustrial

# Postal address (add as many lines as necessary)
address:
  - line: PO Box 121
  - line: Florence, CO 81226

# Credits content
credits: 'This website was built using Freelancer, a free to use & open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
